export const SITE_SETTING_SLOGAN_REQUESTED = 'SITE_SETTING_SLOGAN_REQUESTED';
export const SITE_SETTING_SLOGAN_SUCCESS = 'SITE_SETTING_SLOGAN_SUCCESS';
export const SITE_SETTING_SLOGAN_FAILED = 'SITE_SETTING_SLOGAN_FAILED';